services:
  db:
    image: postgis/postgis:14-3.4 # Postgres + PostGIS image
    container_name: city-issue-tracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    #restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: city-issue-tracker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbitmq_pass_123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    #restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: city-issue-tracker-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    #restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: city-issue-tracker-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    #restart: unless-stopped

volumes:
  rabbitmq_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
